travis:
  secure:
    BINSTAR_TOKEN: LlAqWo1tqQH3vXKh2kS7x3swqrI6sy5VoaaMNhRkDITBYgGSGmnlV7WWj122prrTrB329wGEifbUy8yTkbroqVUhRQrLpP84uv95GoKLrghZTCHSGa55zLdlStmpYDUANvT65h6jYLTzzHba7GWmTk76l3/HyBl5eSUzl9uJNx979wSVj0UkxvXzy1PKhkXdg/zWBK4Lri1MIW3qWSEZ4BvatBM2/2MlgzWwkmHImvFP5wWCzYYrkermkOqrUm+4sGbcZc+/ZvN71co6mK+sHoLXy8lOxh14up2VhAwX8yVUWSK7aXohfuxNlZwsGddXoI5lTuWYPYhwR40q77HD0G6+p2xak7GgdVZUGMvJcka9W+g/ltxAiFXOUUvq5Bt8D8Ws15eLxHrTXHK7S5xkEVpDp7ggnOzpTyM3Nm0x9O9gjeFYCk6d0Rk/PheQ7E+rQ0Edg4pivgejqf4NY4RNkKWMutkFkwyJHM+9ZpzqBZHzM8hwH6pH0Xy+02Ob+Bllwg5tH7AcHQQPUm2l3tVAZa87ZVKODXkuDXCzgaJTbi+MPgelr5UrbCAgBmvOYzBz++wWTuasGS6aAbghyQg7/42aevn7ut/w00Votr5LpMDKr0Thxqb3Ih2fDaqk70bIlB/9en5HOw8VfE2HBIZMzSx9KSsaWu50wDol2I5G2Lo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
